# These settings are synced to GitHub by https://probot.github.io/apps/settings/
_extends: .github

repository:
  description: ":art: My base blueprint."
  topics: "ivank, blueprint, accelerator, base"
  private: false
  has_issues: true
  has_projects: false
  has_wiki: false
  has_downloads: false
  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true
  delete_branch_on_merge: true
  enable_automated_security_fixes: true
  enable_vulnerability_alerts: false
