#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import logging

from src import app

logging.basicConfig(format="%(asctime)s %(name)s %(levelname)s - %(message)s", level=logging.INFO)
logging.getLogger("wars").setLevel(logging.INFO)

if __name__ == "__main__":
    logging.info("do the stuff")
    app.run()
